version: '3.9'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus-2.47.0.linux-amd64/prometheus.yml
    ports:
      - 8900:8900
    command:
      - '--web.listen-address=:8900'
      - '--config.file=/etc/prometheus-2.47.0.linux-amd64/prometheus.yml'
    networks:
      - promnet
    user: root
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./grafana-volume:/var/lib/grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - promnet
    user: root
    depends_on:
      - prometheus

networks:
  promnet:
    driver: bridge
    