version: '3.9'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/config/:/etc/prometheus/
      - ./prometheus-volume:/prometheus
    ports:
      - 8900:8900
    command:
      - '--web.enable-lifecycle'
      - '--web.listen-address=:8900'
      - '--config.file=/etc/prometheus/prometheus.yml'
    user: root
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./grafana-volume:/var/lib/grafana
    restart: always
    ports:
      - 3000:3000
    user: root
    depends_on:
      - prometheus

networks:
  default:
    driver: bridge
    name: service-network
    